version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - mynetwork

  app:
    build: .
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    volumes:
      - .:/app
      - ./OCR_data:/app/OCR_data  # Ensure this path matches your local directory structure
      - ./chroma_db:/app/chroma_db  # Ensure this path matches your local directory structure
    environment:
      - CHROMA_DIR=/app/chroma_db
      - OCR_DIR=/app/OCR_data
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
