version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    volumes:
      - ./data:/app/OCR_data  # Ensure this path matches your local directory structure
      - ./chroma_db:/app/chroma_db  # Ensure this path matches your local directory structure
    environment:
      - CHROMA_DIR=/app/chroma_db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
